name: Visual Diff
on: pull_request
jobs:
  build:
    name: Visual Diff
    timeout-minutes: 10
    runs-on: [self-hosted, Linux, AWS]
    steps:
      - uses: Brightspace/third-party-actions@actions/checkout
      - uses: Brightspace/third-party-actions@actions/setup-node
        with:
          node-version-file: .nvmrc
      - name: Add CodeArtifact npm registry
        uses: Brightspace/codeartifact-actions/npm/add-registry@v1.5.1
        with:
          auth-token: '${{secrets.CODEARTIFACT_AUTH_TOKEN}}'
      - name: Install Dependencies
        run: npm install
      - name: Visual Diff Tests
        uses: BrightspaceUI/actions/visual-diff@main
        with:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_SESSION_TOKEN: ${{ secrets.AWS_SESSION_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
